name: tests
on: [push]

jobs:
  test:
    name: tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Npm install
        run: npm install
      - name: Run TestCafe
        run : npm test
